name: SEO Automation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  seo:
    runs-on: ubuntu-latest

    if: |
      !contains(github.event.head_commit.message, 'auto-seo')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Gerar SEO
        run: node gerador-seo.js

      - name: Commit SEO
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add sitemap.xml robots.txt *.txt

          git diff --cached --quiet || \
          git commit -m "auto-seo"

          git push

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: seo

    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - uses: actions/deploy-pages@v4
